spring.application.name=demo
server.port=8084

# =========== MYSQL ===========
spring.datasource.url=jdbc:mysql://localhost:3306/ReaderApiGutendex

spring.datasource.username=GutendexApi
spring.datasource.password=GutendeX12.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========== JPA / HIBERNATE ===========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========== LOGGING ===========
spring.jpa.properties.hibernate.generate_statistics=false